apiVersion: v1
kind: Service
metadata:
  name: frontendapp-svc
  namespace: frontendapplication
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000  
  selector:
    app: frontendapp